# Generated by Django 5.0.4 on 2024-05-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
